### ISSUE TITLE
下载权重跑eval模式报错

### ISSUE THREAD

**Issue by liuxi1234** [argusswift/YOLOv4-pytorch#102]
刚开始报错：
`FileNotFoundError: [Errno 2] No such file or directory: 'F:\\code\\YOLOv4-pytorch-master-attention\\log_val\\log_voc_val.txt'`
创建了空文件log_voc_val.txt之后，又报错：
Traceback (most recent call last):
  File "eval_voc.py", line 147, in <module>
    visiual=opt.visiual,
  File "eval_voc.py", line 35, in __init__
    self.__load_model_weights(weight_path)
  File "eval_voc.py", line 43, in __load_model_weights
    chkpt = torch.load(weight, map_location=self.__device)
  File "F:\anaconda\lib\site-packages\torch\serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "F:\anaconda\lib\site-packages\torch\serialization.py", line 755, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x00'.
，请问怎么解决？

**Comment by chm5174** [comment]
权重文件config中所选模型不匹配

**Comment by liuxi1234** [comment]
直接用该仓库预训练权重文件也会产生不匹配的问题吗？

**Comment by chm5174** [comment]
> 直接用该仓库预训练权重文件也会产生不匹配的问题吗？

我之前遇到这问题就是config里选了带MobileNetV3的yolo，但用的权重文件是yolov4.weight，换了其他预训练模型就可以了。

**Comment by WispX-1117** [comment]
老哥 怎么解决的
