### ISSUE TITLE
IndexError: index 14 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by lilangyi** [argusswift/YOLOv4-pytorch#116]
Traceback (most recent call last):
  File "train.py", line 357, in <module>
    fp_16=opt.fp_16,
  File "train.py", line 165, in train
    ) in enumerate(self.train_dataloader):
  File "/home/lee/anaconda3/envs/pytorch_1.5_py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/lee/anaconda3/envs/pytorch_1.5_py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/lee/anaconda3/envs/pytorch_1.5_py3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lee/anaconda3/envs/pytorch_1.5_py3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lee/Desktop/myfiles/20-12-21-pytorch-yolov4/YOLOv4-PyTorch/utils/datasets.py", line 59, in __getitem__
    ) = self.__creat_label(bboxes)
  File "/home/lee/Desktop/myfiles/20-12-21-pytorch-yolov4/YOLOv4-PyTorch/utils/datasets.py", line 168, in __creat_label
    one_hot[bbox_class_ind] = 1.0
IndexError: index 14 is out of bounds for axis 0 with size 1

执行训练的时候这是哪里出问题了呢

**Comment by argusswift** [comment]
> Traceback (most recent call last):
> File "train.py", line 357, in
> fp_16=opt.fp_16,
> File "train.py", line 165, in train
> ) in enumerate(self.train_dataloader):
> File "/home/lee/anaconda3/envs/pytorch_1.5_py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in **next**
> data = self._next_data()
> File "/home/lee/anaconda3/envs/pytorch_1.5_py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
> data = self._dataset_fetcher.fetch(index) # may raise StopIteration
> File "/home/lee/anaconda3/envs/pytorch_1.5_py3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/lee/anaconda3/envs/pytorch_1.5_py3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "/home/lee/Desktop/myfiles/20-12-21-pytorch-yolov4/YOLOv4-PyTorch/utils/datasets.py", line 59, in **getitem**
> ) = self.__creat_label(bboxes)
> File "/home/lee/Desktop/myfiles/20-12-21-pytorch-yolov4/YOLOv4-PyTorch/utils/datasets.py", line 168, in __creat_label
> one_hot[bbox_class_ind] = 1.0
> IndexError: index 14 is out of bounds for axis 0 with size 1
> 
> 执行训练的时候这是哪里出问题了呢

请检查标签
