### ISSUE TITLE
CUDA_VISIBLE_DEVICES=0 python3 eval_voc.py --weight_path weight/best.pt --gpu_id 0 --eval --mode det

### ISSUE THREAD

**Issue by lilangyi** [argusswift/YOLOv4-pytorch#127]
在进行detect的时候执行CUDA_VISIBLE_DEVICES=0 python3 eval_voc.py --weight_path weight/best.pt --gpu_id 0 --eval --mode det

保错如下：
Traceback (most recent call last):
  File "eval_voc.py", line 150, in <module>
    visiual=opt.visiual,
  File "eval_voc.py", line 79, in detection
    bboxes_prd = self.__evalter.get_bbox(img, v)
  File "/home/lee/Desktop/myfiles/20-12-21-pytorch-yolov4/YOLOv4-PyTorch/eval/evaluator.py", line 99, in get_bbox
    self.__predict(img, test_input_size, valid_scale)
  File "/home/lee/Desktop/myfiles/20-12-21-pytorch-yolov4/YOLOv4-PyTorch/eval/evaluator.py", line 126, in __predict
    _, p_d, beta = self.model(img)
ValueError: not enough values to unpack (expected 3, got 2)

该如何解决呢

**Comment by li-yan-type** [comment]
eval_voc.py文件第59行 self.__model, showatt=False.改为self.__model, showatt=True

**Comment by jingtianyilong** [comment]
If you update to the latest version you should see the attention block. And you can set `showatt` to `True`. Otherwise, I would suggest that you abandon the attention part.

**Comment by lilangyi** [comment]
> If you update to the latest version you should see the attention block. And you can set `showatt` to `True`. Otherwise, I would suggest that you abandon the attention part.

感谢

**Comment by lilangyi** [comment]
> eval_voc.py文件第59行 self.__model, showatt=False.改为self.__model, showatt=True

感谢

**Comment by gja-bit** [comment]
Traceback (most recent call last):
  File "C:/Users/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py", line 148, in <module>
    mode=opt.mode
  File "C:/Users/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py", line 38, in __init__
    self.__load_model_weights(weight_path)
  File "C:/Users/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py", line 47, in __load_model_weights
    self.__model.load_state_dict(chkpt["model"])
KeyError: 'model'
该如何解决

**Comment by li-yan-type** [comment]
> Traceback (most recent call last):
> File "C:/Users/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py", line 148, in
> mode=opt.mode
> File "C:/Users/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py", line 38, in **init**
> self.__load_model_weights(weight_path)
> File "C:/Users/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py", line 47, in __load_model_weights
> self.__model.load_state_dict(chkpt["model"])
> KeyError: 'model'
> 该如何解决

当你使用可视化时，需要重新训练你的的预训练模型

**Comment by minuet-red** [comment]
> Traceback (most recent call last):
> File "C:/Users/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py", line 148, in
> mode=opt.mode
> File "C:/Users/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py", line 38, in **init**
> self.__load_model_weights(weight_path)
> File "C:/Users/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py", line 47, in __load_model_weights
> self.__model.load_state_dict(chkpt["model"])
> KeyError: 'model'
> 该如何解决

好兄弟你这个问题怎么解决的？我也遇到同样的问题了

**Comment by lilangyi** [comment]
> > 追溯（最近一次通话）：
> > 文件“ C：/Users/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py”，行148，在
> > mode = opt.mode
> > 文件中，“ C：/用户/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py”，第38行，位于**初始化**
> > 自我中。__load_model_weights（weight_path）
> > 文件“ C：/ Users / gja / Downloads / YOLOv4-pytorch-master” /YOLOv4-pytorch-master/eval_voc.py“，第47行，位于__load_model_weights 
> > self .__ model.load_state_dict（chkpt [” model“]）
> > KeyError：'model'
> > 该如何解决
> 
> 好兄弟你这个问题怎么解决的？我也遇到同样的问题了
self .__ model.load_state_dict（chkpt [” model“]）修改为：self .__ model.load_state_dict（chkpt）

**Comment by minuet-red** [comment]
> > > 追溯（最近一次通话）：
> > > 文件“ C：/Users/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py”，行148，在
> > > mode = opt.mode
> > > 文件中，“ C：/用户/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py”，第38行，位于**初始化**
> > > 自我中。**load_model_weights（weight_path）
> > > 文件“ C：/ Users / gja / Downloads / YOLOv4-pytorch-master” /YOLOv4-pytorch-master/eval_voc.py“，第47行，位于__load_model_weights
> > > self .** model.load_state_dict（chkpt [” model“]）
> > > KeyError：'model'
> > > 该如何解决
> > 
> > 
> > 好兄弟你这个问题怎么解决的？我也遇到同样的问题了
> > self .__ model.load_state_dict（chkpt [” model“]）修改为：self .__ model.load_state_dict（chkpt）

感谢

**Comment by inuxer** [comment]
> > Traceback (most recent call last):
> > File "C:/Users/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py", line 148, in
> > mode=opt.mode
> > File "C:/Users/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py", line 38, in **init**
> > self.__load_model_weights(weight_path)
> > File "C:/Users/gja/Downloads/YOLOv4-pytorch-master/YOLOv4-pytorch-master/eval_voc.py", line 47, in __load_model_weights
> > self.__model.load_state_dict(chkpt["model"])
> > KeyError: 'model'
> > 该如何解决
> 
> 当你使用可视化时，需要重新训练你的的预训练模型

直接用题主训练好的模型，没办法直接显示注意力的热力图吗？
