### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by lccui** [argusswift/YOLOv4-pytorch#135]
Saving cached annotations to D:/code/detect/YOLOv4-pytorch/data\pred_result\cache\annots.pkl
Traceback (most recent call last):
  File "train.py", line 211, in <module>
    fp_16=opt.fp_16).train()
  File "train.py", line 166, in train
    APs, inference_time = Evaluator(self.yolov4, showatt=False).APs_voc()
  File "D:\code\detect\YOLOv4-pytorch\eval\evaluator.py", line 65, in APs_voc
    return self.__calc_APs(), self.inference_time
  File "D:\code\detect\YOLOv4-pytorch\eval\evaluator.py", line 172, in __calc_APs
    R, P, AP = voc_eval.voc_eval(filename, annopath, imagesetfile, cls, cachedir, iou_thresh, use_07_metric)
  File "D:\code\detect\YOLOv4-pytorch\eval\voc_eval.py", line 143, in voc_eval
    BB = np.array([[float(z) for z in x[2:]] for x in splitlines])
  File "D:\code\detect\YOLOv4-pytorch\eval\voc_eval.py", line 143, in <listcomp>
    BB = np.array([[float(z) for z in x[2:]] for x in splitlines])
MemoryError

**Comment by argusswift** [comment]
> MemoryError

MemoryError是你内存溢出的问题

**Comment by cymdhx** [comment]
> > MemoryError
> 
> MemoryError是你内存溢出的问题

![image](https://user-images.githubusercontent.com/73769530/104931964-171a1b80-59e2-11eb-80c6-11d7cc4944f7.png)
感觉这应该是代码val部分错了 之前老代码没有这错误

**Comment by cymdhx** [comment]
![Uploading image.png…]()

**Comment by cymdhx** [comment]
总之就是一道val就报错
