### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by leiqing110** [argusswift/YOLOv4-pytorch#148]
执行evaluator过程出现错误
Traceback (most recent call last):
  File "g:\GitHub_work\YOLOv4-pytorch\train.py", line 365, in <module>
    fp_16=opt.fp_16,
  File "g:\GitHub_work\YOLOv4-pytorch\train.py", line 280, in train
    self.yolov4, showatt=self.showatt
  File "g:\GitHub_work\YOLOv4-pytorch\eval\evaluator.py", line 63, in APs_voc
    for i, _ in enumerate(pool.imap_unordered(self.Single_APs_voc, img_inds)):
  File "H:\Anaconda3\envs\open-mmlab\lib\multiprocessing\pool.py", line 748, in next
    raise value
  File "H:\Anaconda3\envs\open-mmlab\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "g:\GitHub_work\YOLOv4-pytorch\eval\evaluator.py", line 75, in Single_APs_voc
    bboxes_prd = self.get_bbox(img, self.multi_scale_test, self.flip_test)
  File "g:\GitHub_work\YOLOv4-pytorch\eval\evaluator.py", line 119, in get_bbox
    bboxes = self.__predict(img, self.val_shape, (0, np.inf), mode)
  File "g:\GitHub_work\YOLOv4-pytorch\eval\evaluator.py", line 127, in __predict
    org_h, org_w, _ = org_img.shape
ValueError: not enough values to unpack (expected 3, got 0)

**Comment by Yolanda2020** [comment]
I have met the same problem, could you please telll me how to solve it if you have an anwer?

**Comment by Sarouch** [comment]
> I have met the same problem, could you please telll me how to solve it if you have an anwer?

@leiqing110  @Yolanda2020 , please did you find out a solution for this ? I have the same problem. Thanks
