### ISSUE TITLE
i meet some troublle when i train my model with attention moudle.please give me some advices

### ISSUE THREAD

**Issue by yichanshiwoa** [argusswift/YOLOv4-pytorch#161]
ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig'

**Comment by argusswift** [comment]
> ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig'

Please give more details

**Comment by yichanshiwoa** [comment]
> > ImportError: cannot import name 'UnencryptedCookieSessionFactoryConfig'
> 
> Please give more details
Thanks for your reply, i have resolve this problem.but i got a new error,when i run eval.voc.py. the model which i train on my data. My movation is got the heatmap to see the attention.The wrong message in th belowing :
Traceback (most recent call last):
  File "/home/sxw/YOLOv4-pytorch-master/eval_voc.py", line 139, in <module>
    mode=opt.mode
  File "/home/sxw/YOLOv4-pytorch-master/eval_voc.py", line 36, in __init__
    self.__evalter = Evaluator(self.__model, showatt=self.__showatt)
  File "/home/sxw/YOLOv4-pytorch-master/eval/evaluator.py", line 13, in __init__
    if cfg.TRAIN.DATA_TYPE == 'VOC':
AttributeError: 'dict' object has no attribute 'DATA_TYPE'

**Comment by cqray1990** [comment]
@yichanshiwoa  how did solove it , i meet this too?
