### ISSUE TITLE
用自己的数据训练出来模型之后，运行eval_voc.py出不来类热度图，报了下面的错误。

### ISSUE THREAD

**Issue by yichanshiwoa** [argusswift/YOLOv4-pytorch#163]
Traceback (most recent call last):
  File "/home/sxw/YOLOv4-pytorch-master/eval_voc.py", line 146, in <module>
    mode=opt.mode
  File "/home/sxw/YOLOv4-pytorch-master/eval_voc.py", line 36, in __init__
    self.__evalter = Evaluator(self.__model, showatt=self.__showatt)
  File "/home/sxw/YOLOv4-pytorch-master/eval/evaluator.py", line 13, in __init__
    if cfg.TRAIN.DATA_TYPE == 'VOC':
AttributeError: 'dict' object has no attribute 'DATA_TYPE'

**Comment by Zpadger** [comment]
@yichanshiwoa 请问你问题解决了吗？我也是用作者提供的eval_voc.py加载模型报错
