### ISSUE TITLE
成功复现了该厂库的代码，大家可以贴出自己遇到的问题，希望对家有帮助，最后感谢作者。

### ISSUE THREAD

**Issue by yichanshiwoa** [argusswift/YOLOv4-pytorch#164]
欢迎大家贴出自己遇到的bug,互相交流。

**Comment by argusswift** [comment]
> 欢迎大家贴出自己遇到的bug,互相交流。

感谢为本仓库做出的努力，大家一起互相交流。

**Comment by 442616159** [comment]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed我跑训练时出现这个问题

**Comment by yichanshiwoa** [comment]
> IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed我跑训练时出现这个问题
麻烦贴出你的报错代码，这样有助于找出问题所在。

**Comment by seven060422** [comment]
请问你能发一份源码或者写一个复现的博客嘛

**Comment by yichanshiwoa** [comment]
你可以把问题帖出来。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: seven060422 ***@***.***&gt;
发送时间: 2021年4月15日 20:24
收件人: argusswift/YOLOv4-pytorch ***@***.***&gt;
抄送: yichanshiwoa ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[argusswift/YOLOv4-pytorch] 成功复现了该厂库的代码，大家可以贴出自己遇到的问题，希望对家有帮助，最后感谢作者。 (#164)





 
请问你能发一份源码或者写一个复现的博客嘛

**Comment by 442616159** [comment]
训练的时候为什么学习率都是0啊？

**Comment by argusswift** [comment]
> 训练的时候为什么学习率都是0啊？

显示精度的问题，建议设置为输出小数点后8位

**Comment by yichanshiwoa** [comment]
你是不是预加载权重了，你可以不预加载权重会出现损失函数。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Tomas Yang ***@***.***&gt;
发送时间: 2021年4月21日 16:49
收件人: argusswift/YOLOv4-pytorch ***@***.***&gt;
抄送: yichanshiwoa ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[argusswift/YOLOv4-pytorch] 成功复现了该厂库的代码，大家可以贴出自己遇到的问题，希望对家有帮助，最后感谢作者。 (#164)





  
训练的时候为什么学习率都是0啊？
  
显示精度的问题，建议设置为输出小数点后8位

**Comment by sjfei** [comment]
yolov4训练自己数据集损失一直出现nan
![屏幕截图 2021-05-13 121310](https://user-images.githubusercontent.com/33625759/118078048-ed00c500-b3e7-11eb-943c-cb1e7db175d7.png)

**Comment by yichanshiwoa** [comment]
数据集多大&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sjfei ***@***.***&gt;
发送时间: 2021年5月13日 12:37
收件人: argusswift/YOLOv4-pytorch ***@***.***&gt;
抄送: yichanshiwoa ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[argusswift/YOLOv4-pytorch] 成功复现了该厂库的代码，大家可以贴出自己遇到的问题，希望对家有帮助，最后感谢作者。 (#164)





 
yolov4训练自己数据集损失一直出现nan

**Comment by sjfei** [comment]
> 数据集多大&nbsp; 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: sjfei ***@***.***&gt; 发送时间: 2021年5月13日 12:37 收件人: argusswift/YOLOv4-pytorch ***@***.***&gt; 抄送: yichanshiwoa ***@***.***&gt;, Author ***@***.***&gt; 主题: 回复：[argusswift/YOLOv4-pytorch] 成功复现了该厂库的代码，大家可以贴出自己遇到的问题，希望对家有帮助，最后感谢作者。 (#164) yolov4训练自己数据集损失一直出现nan — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
1400张，10个类别

**Comment by sjfei** [comment]
1400张，10个类别 @yichanshiwoa

**Comment by wasedd** [comment]
这是什么情况，路径下有文件，却显示错误。

`[2021-05-18 16:41:16,036]-[train.py line:279]:===== Validate ===== 
[2021-05-18 16:41:16,036]-[train.py line:281]:val img size is 416 
Traceback (most recent call last):
  File "C:/GitHub/YOLOv4-pytorch/train.py", line 346, in <module>
    fp_16=opt.fp_16,
  File "C:/GitHub/YOLOv4-pytorch/train.py", line 284, in train
    self.yolov4, showatt=self.showatt
  File "C:\GitHub\YOLOv4-pytorch\eval\evaluator.py", line 44, in APs_voc
    with open(img_inds_file, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\GitHub\\YOLOv4-pytorch\\data\\VOCtest-2007\\VOCdevkit\\VOC2007\\ImageSets\\Main\\test.txt'`

其中config文件
`MODEL_TYPE = {
    "TYPE": "YOLOv4"
}  # YOLO type:YOLOv4, Mobilenet-YOLOv4 or Mobilenetv3-YOLOv4

CONV_TYPE = {"TYPE": "DO_CONV"}  # conv type:DO_CONV or GENERAL

ATTENTION = {"TYPE": "NONE"}  # attention type:SEnet、CBAM or NONE

# train
TRAIN = {
    "DATA_TYPE": "VOC",  # DATA_TYPE: VOC ,COCO or Customer
    "TRAIN_IMG_SIZE": 416,
    "AUGMENT": True,
    "BATCH_SIZE": 2,
    "MULTI_SCALE_TRAIN": True,
    "IOU_THRESHOLD_LOSS": 0.5,
    "YOLO_EPOCHS": 50,
    "Mobilenet_YOLO_EPOCHS": 120,
    "NUMBER_WORKERS": 6,
    "MOMENTUM": 0.9,
    "WEIGHT_DECAY": 0.0005,
    "LR_INIT": 1e-4,
    "LR_END": 1e-6,
    "WARMUP_EPOCHS": 2,  # or None
    "showatt": False
}


# val
VAL = {
    "TEST_IMG_SIZE": 416,
    "BATCH_SIZE": 2,
    "NUMBER_WORKERS": 6,
    "CONF_THRESH": 0.005,
    "NMS_THRESH": 0.45,
    "MULTI_SCALE_VAL": False,
    "FLIP_VAL": False,
    "Visual": True,
    "showatt": False
}
VOC_DATA = {
    "NUM": 20,
    "CLASSES": [
        "aeroplane",
        "bicycle",
        "bird",
        "boat",
        "bottle",
        "bus",
        "car",
        "cat",
        "chair",
        "cow",
        "diningtable",
        "dog",
        "horse",
        "motorbike",
        "person",
        "pottedplant",
        "sheep",
        "sofa",
        "train",
        "tvmonitor",
    ],
}`

**Comment by sjfei** [comment]
![屏幕截图 2021-05-20 082646](https://user-images.githubusercontent.com/33625759/118901146-29cb3f80-b945-11eb-816a-471eb0a692ab.png)
eval_voc报错是怎么回事，

**Comment by wasedd** [comment]
运行eval_voc.py后，生成的output文件内容为空，生成的utils\results\images\detections_one_by_one下为空，可以得到pred_result文件结果，但是一张图片对应多个box。请问怎么解决？

**Comment by DreamYH** [comment]
> 欢迎大家贴出自己遇到的bug,互相交流。
你好请问您有使用CBAM的预训练权重么，如果有，方便提供下么，感谢大佬
