### ISSUE TITLE
train

### ISSUE THREAD

**Issue by university-lpf** [argusswift/YOLOv4-pytorch#216]
[2021-07-22 14:27:03,134]-[train.py line:222]:  === Epoch:[  0/50],step:[61010/61108],img_size:[320],total_loss:129.3867|loss_ciou:14.9257|loss_conf:31.2921|loss_cls:83.1709|lr:0.0000 
[2021-07-22 14:27:04,599]-[train.py line:222]:  === Epoch:[  0/50],step:[61020/61108],img_size:[448],total_loss:129.3807|loss_ciou:14.9257|loss_conf:31.2908|loss_cls:83.1661|lr:0.0000 
[2021-07-22 14:27:06,305]-[train.py line:222]:  === Epoch:[  0/50],step:[61030/61108],img_size:[608],total_loss:129.3778|loss_ciou:14.9263|loss_conf:31.2907|loss_cls:83.1628|lr:0.0000 
[2021-07-22 14:27:08,814]-[train.py line:222]:  === Epoch:[  0/50],step:[61040/61108],img_size:[608],total_loss:129.3731|loss_ciou:14.9263|loss_conf:31.2902|loss_cls:83.1585|lr:0.0000 
[2021-07-22 14:27:11,197]-[train.py line:222]:  === Epoch:[  0/50],step:[61050/61108],img_size:[512],total_loss:129.3646|loss_ciou:14.9259|loss_conf:31.2887|loss_cls:83.1519|lr:0.0000 
[2021-07-22 14:27:13,060]-[train.py line:222]:  === Epoch:[  0/50],step:[61060/61108],img_size:[352],total_loss:129.3636|loss_ciou:14.9267|loss_conf:31.2890|loss_cls:83.1497|lr:0.0000 
[2021-07-22 14:27:14,578]-[train.py line:222]:  === Epoch:[  0/50],step:[61070/61108],img_size:[576],total_loss:129.3557|loss_ciou:14.9264|loss_conf:31.2875|loss_cls:83.1437|lr:0.0000 
[2021-07-22 14:27:16,852]-[train.py line:222]:  === Epoch:[  0/50],step:[61080/61108],img_size:[544],total_loss:129.3529|loss_ciou:14.9269|loss_conf:31.2876|loss_cls:83.1403|lr:0.0000 
[2021-07-22 14:27:18,918]-[train.py line:222]:  === Epoch:[  0/50],step:[61090/61108],img_size:[384],total_loss:129.3412|loss_ciou:14.9259|loss_conf:31.2855|loss_cls:83.1318|lr:0.0000 
[2021-07-22 14:27:20,470]-[train.py line:222]:  === Epoch:[  0/50],step:[61100/61108],img_size:[608],total_loss:129.3325|loss_ciou:14.9257|loss_conf:31.2835|loss_cls:83.1252|lr:0.0000 
loading annotations into memory...
Done (t=0.49s)
creating index...
index created!
Traceback (most recent call last):
  File "train.py", line 361, in <module>
    Trainer(
  File "train.py", line 304, in train
    ap50_95, ap50 = evaluator.evaluate(self.yolov4)
  File "/home/lpf/python/yolo/argusswift-YOLOv4-pytorch-master(oringin)/eval/cocoapi_evaluator.py", line 82, in evaluate
    info_img = [float(info) for info in info_img]
  File "/home/lpf/python/yolo/argusswift-YOLOv4-pytorch-master(oringin)/eval/cocoapi_evaluator.py", line 82, in <listcomp>
    info_img = [float(info) for info in info_img]
ValueError: only one element tensors can be converted to Python scalars

新手，我用的是COCO数据集，但是在训练完1轮后进入验证环节就报错，有知道原因的吗

**Comment by argusswift** [comment]
> ValueError: only one element tensors can be converted to Python scalars

这是因为 gpu上的 tensor 不能直接转为float， 需要先在 转为cpu上的张量
