### ISSUE TITLE
train problem

### ISSUE THREAD

**Issue by brightdingpei** [argusswift/YOLOv4-pytorch#24]
Traceback (most recent call last):
  File "D:/code/yolov4/YOLOv4-PyTorch/train.py", line 207, in <module>
    Trainer(weight_path=opt.weight_path,
  File "D:/code/yolov4/YOLOv4-PyTorch/train.py", line 113, in train
    for i, (imgs, label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes)  in enumerate(self.train_dataloader):
  File "D:\anacoda\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "D:\anacoda\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\anacoda\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\anacoda\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\code\yolov4\YOLOv4-PyTorch\utils\datasets.py", line 42, in __getitem__
    img_mix, bboxes_mix = self.__parse_annotation(self.__annotations[item_mix])
  File "D:\code\yolov4\YOLOv4-PyTorch\utils\datasets.py", line 88, in __parse_annotation
    img, bboxes = dataAug.RandomCrop()(np.copy(img), np.copy(bboxes))
  File "D:\code\yolov4\YOLOv4-PyTorch\utils\data_augment.py", line 28, in __call__
    max_bbox = np.concatenate([np.min(bboxes[:, 0:2], axis=0), np.max(bboxes[:, 2:4], axis=0)], axis=-1)
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

Has anyone ever come across this problem

**Comment by argusswift** [comment]
> Traceback (most recent call last):
> File "D:/code/yolov4/YOLOv4-PyTorch/train.py", line 207, in 
> Trainer(weight_path=opt.weight_path,
> File "D:/code/yolov4/YOLOv4-PyTorch/train.py", line 113, in train
> for i, (imgs, label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes) in enumerate(self.train_dataloader):
> File "D:\anacoda\lib\site-packages\torch\utils\data\dataloader.py", line 435, in **next**
> data = self._next_data()
> File "D:\anacoda\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
> data = self._dataset_fetcher.fetch(index) # may raise StopIteration
> File "D:\anacoda\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "D:\anacoda\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in 
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "D:\code\yolov4\YOLOv4-PyTorch\utils\datasets.py", line 42, in **getitem**
> img_mix, bboxes_mix = self.__parse_annotation(self.__annotations[item_mix])
> File "D:\code\yolov4\YOLOv4-PyTorch\utils\datasets.py", line 88, in __parse_annotation
> img, bboxes = dataAug.RandomCrop()(np.copy(img), np.copy(bboxes))
> File "D:\code\yolov4\YOLOv4-PyTorch\utils\data_augment.py", line 28, in **call**
> max_bbox = np.concatenate([np.min(bboxes[:, 0:2], axis=0), np.max(bboxes[:, 2:4], axis=0)], axis=-1)
> IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
> 
> Has anyone ever come across this problem

It seems to be some problems with your own dataset.Please convert your data format to VOC or COCO

**Comment by ForthewinQ** [comment]
> Traceback (most recent call last):
> File "D:/code/yolov4/YOLOv4-PyTorch/train.py", line 207, in
> Trainer(weight_path=opt.weight_path,
> File "D:/code/yolov4/YOLOv4-PyTorch/train.py", line 113, in train
> for i, (imgs, label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes) in enumerate(self.train_dataloader):
> File "D:\anacoda\lib\site-packages\torch\utils\data\dataloader.py", line 435, in **next**
> data = self._next_data()
> File "D:\anacoda\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
> data = self._dataset_fetcher.fetch(index) # may raise StopIteration
> File "D:\anacoda\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in fetch
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "D:\anacoda\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in
> data = [self.dataset[idx] for idx in possibly_batched_index]
> File "D:\code\yolov4\YOLOv4-PyTorch\utils\datasets.py", line 42, in **getitem**
> img_mix, bboxes_mix = self.__parse_annotation(self.__annotations[item_mix])
> File "D:\code\yolov4\YOLOv4-PyTorch\utils\datasets.py", line 88, in __parse_annotation
> img, bboxes = dataAug.RandomCrop()(np.copy(img), np.copy(bboxes))
> File "D:\code\yolov4\YOLOv4-PyTorch\utils\data_augment.py", line 28, in **call**
> max_bbox = np.concatenate([np.min(bboxes[:, 0:2], axis=0), np.max(bboxes[:, 2:4], axis=0)], axis=-1)
> IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
> 
> Has anyone ever come across this problem
我也遇到了   应该是标签里面有空目标的问题

**Comment by kunyaoli** [comment]
> > Traceback (most recent call last):
> > File "D:/code/yolov4/YOLOv4-PyTorch/train.py", line 207, in
> > Trainer(weight_path=opt.weight_path,
> > File "D:/code/yolov4/YOLOv4-PyTorch/train.py", line 113, in train
> > for i, (imgs, label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes) in enumerate(self.train_dataloader):
> > File "D:\anacoda\lib\site-packages\torch\utils\data\dataloader.py", line 435, in **next**
> > data = self._next_data()
> > File "D:\anacoda\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
> > data = self._dataset_fetcher.fetch(index) # may raise StopIteration
> > File "D:\anacoda\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in fetch
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "D:\anacoda\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in
> > data = [self.dataset[idx] for idx in possibly_batched_index]
> > File "D:\code\yolov4\YOLOv4-PyTorch\utils\datasets.py", line 42, in **getitem**
> > img_mix, bboxes_mix = self.__parse_annotation(self.__annotations[item_mix])
> > File "D:\code\yolov4\YOLOv4-PyTorch\utils\datasets.py", line 88, in __parse_annotation
> > img, bboxes = dataAug.RandomCrop()(np.copy(img), np.copy(bboxes))
> > File "D:\code\yolov4\YOLOv4-PyTorch\utils\data_augment.py", line 28, in **call**
> > max_bbox = np.concatenate([np.min(bboxes[:, 0:2], axis=0), np.max(bboxes[:, 2:4], axis=0)], axis=-1)
> > IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
> > Has anyone ever come across this problem
> > 我也遇到了   应该是标签里面有空目标的问题

您好，您训练过程，数据归一化是怎么处理的呢？ 我看voc.py,以及datasets里面好像没有归一化操作。train_annotations.txt里面的坐标不是0-1的

**Comment by ForthewinQ** [comment]
> > > Traceback (most recent call last):
> > > File "D:/code/yolov4/YOLOv4-PyTorch/train.py", line 207, in
> > > Trainer(weight_path=opt.weight_path,
> > > File "D:/code/yolov4/YOLOv4-PyTorch/train.py", line 113, in train
> > > for i, (imgs, label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes) in enumerate(self.train_dataloader):
> > > File "D:\anacoda\lib\site-packages\torch\utils\data\dataloader.py", line 435, in **next**
> > > data = self._next_data()
> > > File "D:\anacoda\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
> > > data = self._dataset_fetcher.fetch(index) # may raise StopIteration
> > > File "D:\anacoda\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in fetch
> > > data = [self.dataset[idx] for idx in possibly_batched_index]
> > > File "D:\anacoda\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in
> > > data = [self.dataset[idx] for idx in possibly_batched_index]
> > > File "D:\code\yolov4\YOLOv4-PyTorch\utils\datasets.py", line 42, in **getitem**
> > > img_mix, bboxes_mix = self.__parse_annotation(self.__annotations[item_mix])
> > > File "D:\code\yolov4\YOLOv4-PyTorch\utils\datasets.py", line 88, in __parse_annotation
> > > img, bboxes = dataAug.RandomCrop()(np.copy(img), np.copy(bboxes))
> > > File "D:\code\yolov4\YOLOv4-PyTorch\utils\data_augment.py", line 28, in **call**
> > > max_bbox = np.concatenate([np.min(bboxes[:, 0:2], axis=0), np.max(bboxes[:, 2:4], axis=0)], axis=-1)
> > > IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
> > > Has anyone ever come across this problem
> > > 我也遇到了   应该是标签里面有空目标的问题
> 
> 您好，您训练过程，数据归一化是怎么处理的呢？ 我看voc.py,以及datasets里面好像没有归一化操作。train_annotations.txt里面的坐标不是0-1的

你是指把标签转化成0,1,2,3 这种吗   这个在voc.py里面有的
 class_id = classes.index(obj.find("name").text.lower().strip())

**Comment by brightdingpei** [comment]
thank you very much，it‘s ok

**Comment by kunyaoli** [comment]
> > > > Traceback (most recent call last):
> > > > File "D:/code/yolov4/YOLOv4-PyTorch/train.py", line 207, in
> > > > Trainer(weight_path=opt.weight_path,
> > > > File "D:/code/yolov4/YOLOv4-PyTorch/train.py", line 113, in train
> > > > for i, (imgs, label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes) in enumerate(self.train_dataloader):
> > > > File "D:\anacoda\lib\site-packages\torch\utils\data\dataloader.py", line 435, in **next**
> > > > data = self._next_data()
> > > > File "D:\anacoda\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
> > > > data = self._dataset_fetcher.fetch(index) # may raise StopIteration
> > > > File "D:\anacoda\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in fetch
> > > > data = [self.dataset[idx] for idx in possibly_batched_index]
> > > > File "D:\anacoda\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in
> > > > data = [self.dataset[idx] for idx in possibly_batched_index]
> > > > File "D:\code\yolov4\YOLOv4-PyTorch\utils\datasets.py", line 42, in **getitem**
> > > > img_mix, bboxes_mix = self.__parse_annotation(self.__annotations[item_mix])
> > > > File "D:\code\yolov4\YOLOv4-PyTorch\utils\datasets.py", line 88, in __parse_annotation
> > > > img, bboxes = dataAug.RandomCrop()(np.copy(img), np.copy(bboxes))
> > > > File "D:\code\yolov4\YOLOv4-PyTorch\utils\data_augment.py", line 28, in **call**
> > > > max_bbox = np.concatenate([np.min(bboxes[:, 0:2], axis=0), np.max(bboxes[:, 2:4], axis=0)], axis=-1)
> > > > IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
> > > > Has anyone ever come across this problem
> > > > 我也遇到了   应该是标签里面有空目标的问题
> > 
> > 
> > 您好，您训练过程，数据归一化是怎么处理的呢？ 我看voc.py,以及datasets里面好像没有归一化操作。train_annotations.txt里面的坐标不是0-1的
> 
> 你是指把标签转化成0,1,2,3 这种吗 这个在voc.py里面有的
> class_id = classes.index(obj.find("name").text.lower().strip())

 不是这个，是box的归一化，我看yolov3有这个操作，然后yoloV3的train.txt,后面的数据都是0-1的，运行博主的VOC.py之后好像没有归一化，不知道是不是把自己把train.txt做个归一化就可以了？`def convert(size, box):
    dw = 1./(size[0])
    dh = 1./(size[1])
    x = (box[0] + box[1])/2.0 - 1
    y = (box[2] + box[3])/2.0 - 1
    w = box[1] - box[0]
    h = box[3] - box[2]
    x = x*dw
    w = w*dw
    y = y*dh
    h = h*dh
    return (x,y,w,h)`

**Comment by ForthewinQ** [comment]
> > > > > Traceback (most recent call last):
> > > > > File "D:/code/yolov4/YOLOv4-PyTorch/train.py", line 207, in
> > > > > Trainer(weight_path=opt.weight_path,
> > > > > File "D:/code/yolov4/YOLOv4-PyTorch/train.py", line 113, in train
> > > > > for i, (imgs, label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes) in enumerate(self.train_dataloader):
> > > > > File "D:\anacoda\lib\site-packages\torch\utils\data\dataloader.py", line 435, in **next**
> > > > > data = self._next_data()
> > > > > File "D:\anacoda\lib\site-packages\torch\utils\data\dataloader.py", line 475, in _next_data
> > > > > data = self._dataset_fetcher.fetch(index) # may raise StopIteration
> > > > > File "D:\anacoda\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in fetch
> > > > > data = [self.dataset[idx] for idx in possibly_batched_index]
> > > > > File "D:\anacoda\lib\site-packages\torch\utils\data_utils\fetch.py", line 44, in
> > > > > data = [self.dataset[idx] for idx in possibly_batched_index]
> > > > > File "D:\code\yolov4\YOLOv4-PyTorch\utils\datasets.py", line 42, in **getitem**
> > > > > img_mix, bboxes_mix = self.__parse_annotation(self.__annotations[item_mix])
> > > > > File "D:\code\yolov4\YOLOv4-PyTorch\utils\datasets.py", line 88, in __parse_annotation
> > > > > img, bboxes = dataAug.RandomCrop()(np.copy(img), np.copy(bboxes))
> > > > > File "D:\code\yolov4\YOLOv4-PyTorch\utils\data_augment.py", line 28, in **call**
> > > > > max_bbox = np.concatenate([np.min(bboxes[:, 0:2], axis=0), np.max(bboxes[:, 2:4], axis=0)], axis=-1)
> > > > > IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
> > > > > Has anyone ever come across this problem
> > > > > 我也遇到了   应该是标签里面有空目标的问题
> > > 
> > > 
> > > 您好，您训练过程，数据归一化是怎么处理的呢？ 我看voc.py,以及datasets里面好像没有归一化操作。train_annotations.txt里面的坐标不是0-1的
> > 
> > 
> > 你是指把标签转化成0,1,2,3 这种吗 这个在voc.py里面有的
> > class_id = classes.index(obj.find("name").text.lower().strip())
> 
> 不是这个，是box的归一化，我看yolov3有这个操作，然后yoloV3的train.txt,后面的数据都是0-1的，运行博主的VOC.py之后好像没有归一化，不知道是不是把自己把train.txt做个归一化就可以了？`def convert(size, box): dw = 1./(size[0]) dh = 1./(size[1]) x = (box[0] + box[1])/2.0 - 1 y = (box[2] + box[3])/2.0 - 1 w = box[1] - box[0] h = box[3] - box[2] x = x*dw w = w*dw y = y*dh h = h*dh return (x,y,w,h)`

昂昂  这个不需要  这只是标签的两种格式  博主的代码就是用的非归一化的格式
