### ISSUE TITLE
The second epoch

### ISSUE THREAD

**Issue by April4lu** [argusswift/YOLOv4-pytorch#47]

**Comment by argusswift** [comment]
> _No description provided._

不太清楚你的问题

**Comment by April4lu** [comment]
感谢及时回复，遇到的问题是
`[2020-10-15 03:47:31,819]-[train.py line:177]:  ===test mAP:0.466 
[2020-10-15 03:47:31,820]-[train.py line:191]:  ===cost time:1189.2994s 
[2020-10-15 03:47:31,824]-[train.py line:112]:===Epoch:[1/50]=== 
^CTraceback (most recent call last):
  File "train.py", line 212, in <module>
  File "train.py", line 113, in train
    for i, (imgs, label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes)  in enumerate(self.train_dataloader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 798, in _get_data
    success, data = self._try_get_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.6/queue.py", line 173, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt`

当一个epoch val结束之后，下一个epoch中的训练就卡住了，还不知道是什么问题

**Comment by sakurasakura1996** [comment]
[2020-10-15 17:02:53,631]-[train.py line:172]:inference time: 49.64 ms 
[2020-10-15 17:02:58,179]-[train.py line:175]:save weights done 
[2020-10-15 17:02:58,180]-[train.py line:176]:  ===test mAP:0.186 
[2020-10-15 17:02:58,180]-[train.py line:190]:  ===cost time:2472.3022s 
[2020-10-15 17:02:58,183]-[train.py line:112]:===Epoch:[1/50]=== 
我也遇到了这个问题，我是在利用云端算力的时候遇到了该问题，在本地主机上训练的时候并没有出现这个问题。

**Comment by argusswift** [comment]
> 感谢及时回复，遇到的问题是
> `[2020-10-15 03:47:31,819]-[train.py line:177]: ===test mAP:0.466
> 
> [2020-10-15 03:47:31,820]-[train.py line:191]: ===cost time:1189.2994s
> 
> [2020-10-15 03:47:31,824]-[train.py line:112]:===Epoch:[1/50]===
> 
> ^CTraceback (most recent call last):
> File "train.py", line 212, in
> File "train.py", line 113, in train
> for i, (imgs, label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes) in enumerate(self.train_dataloader):
> File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in **next**
> data = self._next_data()
> File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 841, in _next_data
> idx, data = self._get_data()
> File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 798, in _get_data
> success, data = self._try_get_data()
> File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
> data = self._data_queue.get(timeout=timeout)
> File "/usr/lib/python3.6/queue.py", line 173, in get
> self.not_empty.wait(remaining)
> File "/usr/lib/python3.6/threading.py", line 299, in wait
> gotit = waiter.acquire(True, timeout)
> KeyboardInterrupt`
> 
> 当一个epoch val结束之后，下一个epoch中的训练就卡住了，还不知道是什么问题

应该是启用多线程的原因，你把NUMBER_WORKERS设置成0.

**Comment by April4lu** [comment]
> > 感谢及时回复，遇到的问题是
> > `[2020-10-15 03:47:31,819]-[train.py line:177]: ===test mAP:0.466
> > [2020-10-15 03:47:31,820]-[train.py line:191]: ===cost time:1189.2994s
> > [2020-10-15 03:47:31,824]-[train.py line:112]:===Epoch:[1/50]===
> > ^CTraceback (most recent call last):
> > File "train.py", line 212, in
> > File "train.py", line 113, in train
> > for i, (imgs, label_sbbox, label_mbbox, label_lbbox, sbboxes, mbboxes, lbboxes) in enumerate(self.train_dataloader):
> > File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 345, in **next**
> > data = self._next_data()
> > File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 841, in _next_data
> > idx, data = self._get_data()
> > File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 798, in _get_data
> > success, data = self._try_get_data()
> > File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
> > data = self._data_queue.get(timeout=timeout)
> > File "/usr/lib/python3.6/queue.py", line 173, in get
> > self.not_empty.wait(remaining)
> > File "/usr/lib/python3.6/threading.py", line 299, in wait
> > gotit = waiter.acquire(True, timeout)
> > KeyboardInterrupt`
> > 当一个epoch val结束之后，下一个epoch中的训练就卡住了，还不知道是什么问题
> 
> 应该是启用多线程的原因，你把NUMBER_WORKERS设置成0.

非常感谢，通过将number worker设置为0后可以继续进入下一个epoch。
