### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by wen0618** [argusswift/YOLOv4-pytorch#73]
1. CUDA_VISIBLE_DEVICES=5 python train.py  --weight_path weight/yolov4.pth --gpu_id 5
Traceback (most recent call last):
  File "train.py", line 3, in <module>
    from model.build_model import Build_Model
  File "/home/wxy/AfterMId/YOLOv4-pytorch/model/build_model.py", line 8, in <module>
    from model.YOLOv4 import YOLOv4
  File "/home/wxy/AfterMId/YOLOv4-pytorch/model/YOLOv4.py", line 5, in <module>
    from .backbones.CSPDarknet53 import _BuildCSPDarknet53
  File "/home/wxy/AfterMId/YOLOv4-pytorch/model/backbones/CSPDarknet53.py", line 22, in <module>
    "linear": nn.Identity(),
AttributeError: module 'torch.nn' has no attribute 'Identity'

How to modify the code?

//
2.About weight file:
Could you share the weight files in BaiduYUN ?I can't open the google website.Thanks!

**Comment by argusswift** [comment]
> 1. AttributeError: module 'torch.nn' has no attribute 'Identity'

1.requirement error:torch>=0.4
2.I will upload weight files later.

**Comment by wen0618** [comment]
> > 1. AttributeError: module 'torch.nn' has no attribute 'Identity'
> 
> 1.requirement error:torch>=0
> 2.I will upload weight files later.

Thank you!
