### ISSUE TITLE
训练过程中报错

### ISSUE THREAD

**Issue by moxiaoguai1993** [argusswift/YOLOv4-pytorch#76]
Traceback (most recent call last):
  File "D:/Project_Code/YOLOv4-pytorch-master/train.py", line 360, in <module>
    fp_16=opt.fp_16,
  File "D:/Project_Code/YOLOv4-pytorch-master/train.py", line 164, in train
    ) in enumerate(self.train_dataloader):
  File "C:\ProgramData\Anaconda3\envs\gpupy\lib\site-packages\torch\utils\data\dataloader.py", line 363, in __next__
    data = self._next_data()
  File "C:\ProgramData\Anaconda3\envs\gpupy\lib\site-packages\torch\utils\data\dataloader.py", line 403, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\ProgramData\Anaconda3\envs\gpupy\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\ProgramData\Anaconda3\envs\gpupy\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Project_Code\YOLOv4-pytorch-master\utils\datasets.py", line 45, in __getitem__
    self.__annotations[item_mix]
  File "D:\Project_Code\YOLOv4-pytorch-master\utils\datasets.py", line 113, in __parse_annotation
    img, bboxes = dataAug.RandomCrop()(np.copy(img), np.copy(bboxes))
  File "D:\Project_Code\YOLOv4-pytorch-master\utils\data_augment.py", line 30, in __call__
    np.min(bboxes[:, 0:2], axis=0),
IndexError: too many indices for array

**Comment by cangwang** [comment]
你dataset加载解析有问题，自己断点检查一下

**Comment by moxiaoguai1993** [comment]
> 你dataset加载解析有问题
