### ISSUE TITLE
train issue

### ISSUE THREAD

**Issue by hardworking-jws** [argusswift/YOLOv4-pytorch#8]
[2020-08-28 08:35:20,162]-[train.py line:150]:  === Epoch:[  0/120],step:[  0/42],img_size:[416],total_loss:1939.8105|loss_giou:13.1441|loss_conf:1918.4628|loss_cls:8.2036|lr:0.0000 
[2020-08-28 08:35:21,411]-[train.py line:150]:  === Epoch:[  0/120],step:[ 10/42],img_size:[416],total_loss:1473.7147|loss_giou:15.7401|loss_conf:1448.6389|loss_cls:9.3356|lr:0.0000 
[2020-08-28 08:35:22,632]-[train.py line:150]:  === Epoch:[  0/120],step:[ 20/42],img_size:[416],total_loss:837.1195|loss_giou:12.7785|loss_conf:816.7214|loss_cls:7.6196|lr:0.0000 
[2020-08-28 08:35:23,850]-[train.py line:150]:  === Epoch:[  0/120],step:[ 30/42],img_size:[416],total_loss:582.2850|loss_giou:12.2135|loss_conf:562.8416|loss_cls:7.2298|lr:0.0000 
[2020-08-28 08:35:25,084]-[train.py line:150]:  === Epoch:[  0/120],step:[ 40/42],img_size:[416],total_loss:451.4386|loss_giou:11.3422|loss_conf:433.4202|loss_cls:6.6761|lr:0.0000 
[2020-08-28 08:35:25,324]-[train.py line:167]:===== Validate ===== 
val img size is 416
 96%|#############################################################################################################################1     | 43/45 [00:25<00:01,  1.49it/s]Traceback (most recent call last):
  File "train.py", line 216, in <module>
    fp_16=opt.fp_16).train()
  File "train.py", line 169, in train
    APs, inference_time = Evaluator(self.yolov4, showatt=False).APs_voc()
  File "/home/mist/YOLOv4-pytorch-master/eval/evaluator.py", line 50, in APs_voc
    bboxes_prd = self.get_bbox(img, multi_test, flip_test)
  File "/home/mist/YOLOv4-pytorch-master/eval/evaluator.py", line 84, in get_bbox
    bboxes = self.__predict(img, self.val_shape, (0, np.inf))
  File "/home/mist/YOLOv4-pytorch-master/eval/evaluator.py", line 92, in __predict
    org_h, org_w, _ = org_img.shape
ValueError: not enough values to unpack (expected 3, got 0)

我的数据集很少 但是为什么会出现返回值为0的问题呢 希望您能解答

**Comment by whyisma** [comment]
这个应该是你测试时图片读取出了问题吧，错误显示没有读到图片

**Comment by Yolanda2020** [comment]
请问您后来是如何解决的呢？我也遇到了同样的问题

**Comment by xaioffff** [comment]
> [2020-08-28 08:35:20,162]-[train.py line:150]: === Epoch:[ 0/120],step:[ 0/42],img_size:[416],total_loss:1939.8105|loss_giou:13.1441|loss_conf:1918.4628|loss_cls:8.2036|lr:0.0000 [2020-08-28 08:35:21,411]-[train.py line:150]: === Epoch:[ 0/120],step:[ 10/42],img_size:[416],total_loss:1473.7147|loss_giou:15.7401|loss_conf:1448.6389|loss_cls:9.3356|lr:0.0000 [2020-08-28 08:35:22,632]-[train.py line:150]: === Epoch:[ 0/120],step:[ 20/42],img_size:[416],total_loss:837.1195|loss_giou:12.7785|loss_conf:816.7214|loss_cls:7.6196|lr:0.0000 [2020-08-28 08:35:23,850]-[train.py line:150]: === Epoch:[ 0/120],step:[ 30/42],img_size:[416],total_loss:582.2850|loss_giou:12.2135|loss_conf:562.8416|loss_cls:7.2298|lr:0.0000 [2020-08-28 08:35:25,084]-[train.py line:150]: === Epoch:[ 0/120],step:[ 40/42],img_size:[416],total_loss:451.4386|loss_giou:11.3422|loss_conf:433.4202|loss_cls:6.6761|lr:0.0000 [2020-08-28 08:35:25,324]-[train.py line:167]:===== Validate ===== val img size is 416 96%|#############################################################################################################################1 | 43/45 [00:25<00:01, 1.49it/s]Traceback (most recent call last): File "train.py", line 216, in fp_16=opt.fp_16).train() File "train.py", line 169, in train APs, inference_time = Evaluator(self.yolov4, showatt=False).APs_voc() File "/home/mist/YOLOv4-pytorch-master/eval/evaluator.py", line 50, in APs_voc bboxes_prd = self.get_bbox(img, multi_test, flip_test) File "/home/mist/YOLOv4-pytorch-master/eval/evaluator.py", line 84, in get_bbox bboxes = self.__predict(img, self.val_shape, (0, np.inf)) File "/home/mist/YOLOv4-pytorch-master/eval/evaluator.py", line 92, in __predict org_h, org_w, _ = org_img.shape ValueError: not enough values to unpack (expected 3, got 0)
> 
> 我的数据集很少 但是为什么会出现返回值为0的问题呢 希望您能解答

Senior, how did you solve it?  I also met the same problem, I hope you can reply to me
