### ISSUE TITLE
train issues

### ISSUE THREAD

**Issue by EternalEvan** [argusswift/YOLOv4-pytorch#88]
请问训练时出现这个错误是什么原因呀？

4907|loss_cls:102.4002|lr:0.0000 
[2020-11-12 15:26:27,492]-[train.py line:223]:  === Epoch:[  0/50],step:[22320/22320],img_size:[416],total_loss:151.6319|loss_ciou:15.7647|loss_conf:33.4873|loss_cls:102.3799|lr:0.0000 
loading annotations into memory...
Done (t=0.40s)
creating index...
index created!
Traceback (most recent call last):
  File "train.py", line 360, in <module>
    fp_16=opt.fp_16,
  File "train.py", line 298, in train
    ap50_95, ap50 = evaluator.evaluate(self.yolov4)
  File "/home/zhuyx/YOLOv4-pytorch/eval/cocoapi_evaluator.py", line 82, in evaluate
    info_img = [float(info) for info in info_img]
  File "/home/zhuyx/YOLOv4-pytorch/eval/cocoapi_evaluator.py", line 82, in <listcomp>
    info_img = [float(info) for info in info_img]
ValueError: only one element tensors can be converted to Python scalars

cocoapi_evaluator.py里面相关的代码是这样的：
def evaluate(self, model):

        """

        COCO average precision (AP) Evaluation. Iterate inference on the test dataset

        and the results are evaluated by COCO API.

        Args:

            model : model object

        Returns:

            ap50_95 (float) : calculated COCO AP for IoU=50:95

            ap50 (float) : calculated COCO AP for IoU=50

        """

        model.eval()

        cuda = torch.cuda.is_available()

        Tensor = torch.cuda.FloatTensor if cuda else torch.FloatTensor

        ids = []

        data_dict = []

        dataiterator = iter(self.dataloader)

        while True:  # all the data in val2017

            try:

                img, _, info_img, id_ = next(dataiterator)  # load a batch

            except StopIteration:

                break

            info_img = [float(info) for info in info_img]

            id_ = int(id_)

            ids.append(id_)

**Comment by argusswift** [comment]
> info

info为tensor，这里强制类型转换成float会报错。你试试[float(info.numpy()) for info in info_img]

**Comment by JacobOaks** [comment]
> > info
> 
> info为tensor，这里强制类型转换成float会报错。你试试[float(info.numpy()) for info in info_img]

Also having this issue. This didn't fix it, gave error:

`TypeError: only size-1 arrays can be converted to Python scalars`

**Comment by EternalEvan** [comment]
> > info
> 
> info为tensor，这里强制类型转换成float会报错。你试试[float(info.numpy()) for info in info_img]

谢谢，我用：
            info_img = [info.numpy() for info in info_img];
            id_ = id_.numpy().astype(np.int)
这样的方法解决了这个问题，但这也导致了后面：
  if len(data_dict) > 0:
            cocoGt = self.dataset.coco
            # workaround: temporarily write data to json file because pycocotools can't process dict in py36.
            _, tmp = tempfile.mkstemp()
            print(data_dict)
            json.dump(data_dict, open(tmp, "w"))
出现了问题：TypeError: Object of type ndarray is not JSON serializable

当我试着把data_dict里的元素全部tolist()化了之后：
A = {
                    "image_id": id_.tolist(),
                    "category_id": label,
                    "bbox": bbox,
                    "score": score,
                    "segmentation": [],
                }  # COCO json format
  data_dict.append(A)
  又出现了这样的问题：
  File "/home/zhuyx/YOLOv4-pytorch/eval/cocoapi_evaluator.py", line 129, in evaluate
    cocoDt = cocoGt.loadRes(tmp)
  File "/home/zhuyx/anaconda/envs/yolov4/lib/python3.6/site-packages/pycocotools/coco.py", line 326, in loadRes
    assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
TypeError: unhashable type: 'list'

请问我该怎么解决呀，十分感谢！

**Comment by zyx1996** [comment]
info_img = [info.float() for info in info_img]

**Comment by zyx1996** [comment]
请问你解决这个问题了吗

**Comment by EternalEvan** [comment]
> 请问你解决这个问题了吗
算是解决了吧，你把config里面的val_size设置成1试试应该可以
