### ISSUE TITLE
我使用自己的数据集，在运行python -u train.py --gpu_id 0时出现了 too many indices for array的错误，请问一下应该如何解决

### ISSUE THREAD

**Issue by qi59914** [argusswift/YOLOv4-pytorch#95]
[2020-11-20 10:14:10,781]-[train.py line:155]:===Epoch:[0/120]=== 
Traceback (most recent call last):
  File "train.py", line 360, in <module>
    fp_16=opt.fp_16,
  File "train.py", line 164, in train
    ) in enumerate(self.train_dataloader):
  File "/home/qiyongkang/anaconda3/envs/Y4M3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self.dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/qiyongkang/anaconda3/envs/Y4M3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qiyongkang/anaconda3/envs/Y4M3/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qiyongkang/YOLOv4-pytorch-master/utils/datasets.py", line 45, in __getitem__
    self.__annotations[item_mix]
  File "/home/qiyongkang/YOLOv4-pytorch-master/utils/datasets.py", line 113, in __parse_annotation
    img, bboxes = dataAug.RandomCrop()(np.copy(img), np.copy(bboxes))
  File "/home/qiyongkang/YOLOv4-pytorch-master/utils/data_augment.py", line 30, in __call__
    np.min(bboxes[:, 0:2], axis=0),
IndexError: too many indices for array

**Comment by jingtianyilong** [comment]
print out the bbox and see if you miss anything before this line.
